### ISSUE TITLE
 проблемы с сервисом 25.07.2024

### ISSUE THREAD

**Issue by slavb18** [ilb/cloudtreasury#110]
проблемы с сервисом https://demo.iconicompany.ru/cloudtreasury/calculations
какую бы бумагу не пробовали строить за 23.07 или 24.07 все время выходит сообщение:
"Что-то пошло не так. Проверьте введенный тикер, возможно по нему отсутствуют данные"
и ничего не расчитывается
можно попробовать на бумагах:
ГТЛК 2P-01
ДОМ 1P-14R
ОФЗ 26236
ПочтаР1P10

│ exception NoSuchColumnError: Code not found in [<HTML>].                                                                                                            │
│     at Row.get (/app/node_modules/dataframe-js/lib/row.js:193:15)                                                                                                   │
│     at /app/.next/server/chunks/8250.js:129:55                                                                                                                      │
│     at /app/node_modules/dataframe-js/lib/dataframe.js:700:16                                                                                                       │
│     at createIterGenerator$ (/app/node_modules/dataframe-js/lib/reusables.js:197:25)                                                                                │
│     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)                                                                                            │
│     at Generator.invoke (/app/node_modules/regenerator-runtime/runtime.js:299:22)                                                                                   │
│     at Generator.next (/app/node_modules/regenerator-runtime/runtime.js:124:21)                                                                                     │
│     at Function.from (<anonymous>)                                                                                                                                  │
│     at iter (/app/node_modules/dataframe-js/lib/reusables.js:258:16)                                                                                                │
│     at DataFrame.filter (/app/node_modules/dataframe-js/lib/dataframe.js:699:46)

**Comment by slavb18** [comment]
Починилось рестартом
